[package]
name = "rsw"
version = "0.1.2"
authors = ["dev-tang <dev-tang@foxmail.com>"]

[dependencies]
regex = "0.2"
yaml-rust = "0.3"
comrak = "0.2.5"
clap = {version="2.29.0", features=["yaml"]}
toml = "0.5.1"

[profile.release]
lto = true